// Country list with flag emoji, used by the searchable picker at creation and
// by the Olympic screens. One source, reused everywhere.

export type Country = { name: string; flag: string; code: string };

export const COUNTRIES: Country[] = [
  { name: "United States", flag: "🇺🇸", code: "USA" },
  { name: "Colombia", flag: "🇨🇴", code: "COL" },
  { name: "Argentina", flag: "🇦🇷", code: "ARG" },
  { name: "Spain", flag: "🇪🇸", code: "ESP" },
  { name: "France", flag: "🇫🇷", code: "FRA" },
  { name: "Serbia", flag: "🇷🇸", code: "SRB" },
  { name: "Australia", flag: "🇦🇺", code: "AUS" },
  { name: "Canada", flag: "🇨🇦", code: "CAN" },
  { name: "Germany", flag: "🇩🇪", code: "GER" },
  { name: "Greece", flag: "🇬🇷", code: "GRE" },
  { name: "Slovenia", flag: "🇸🇮", code: "SLO" },
  { name: "Lithuania", flag: "🇱🇹", code: "LTU" },
  { name: "Brazil", flag: "🇧🇷", code: "BRA" },
  { name: "Italy", flag: "🇮🇹", code: "ITA" },
  { name: "Mexico", flag: "🇲🇽", code: "MEX" },
  { name: "Puerto Rico", flag: "🇵🇷", code: "PUR" },
  { name: "Dominican Republic", flag: "🇩🇴", code: "DOM" },
  { name: "Venezuela", flag: "🇻🇪", code: "VEN" },
  { name: "Nigeria", flag: "🇳🇬", code: "NGR" },
  { name: "Japan", flag: "🇯🇵", code: "JPN" },
  { name: "China", flag: "🇨🇳", code: "CHN" },
  { name: "Philippines", flag: "🇵🇭", code: "PHI" },
  { name: "Croatia", flag: "🇭🇷", code: "CRO" },
  { name: "Turkey", flag: "🇹🇷", code: "TUR" },
  { name: "Poland", flag: "🇵🇱", code: "POL" },
  { name: "Israel", flag: "🇮🇱", code: "ISR" },
  { name: "United Kingdom", flag: "🇬🇧", code: "GBR" },
  { name: "Senegal", flag: "🇸🇳", code: "SEN" },
  { name: "Cameroon", flag: "🇨🇲", code: "CMR" },
  { name: "Angola", flag: "🇦🇴", code: "ANG" },
  { name: "New Zealand", flag: "🇳🇿", code: "NZL" },
  { name: "Uruguay", flag: "🇺🇾", code: "URU" },
  { name: "Chile", flag: "🇨🇱", code: "CHI" },
  { name: "Panama", flag: "🇵🇦", code: "PAN" },
  { name: "Ukraine", flag: "🇺🇦", code: "UKR" },
  { name: "Finland", flag: "🇫🇮", code: "FIN" },
  { name: "Latvia", flag: "🇱🇻", code: "LAT" },
  { name: "Montenegro", flag: "🇲🇪", code: "MNE" },
  { name: "Georgia", flag: "🇬🇪", code: "GEO" },
  { name: "South Sudan", flag: "🇸🇸", code: "SSD" },
  { name: "Egypt", flag: "🇪🇬", code: "EGY" },
  { name: "Iran", flag: "🇮🇷", code: "IRI" },
  { name: "South Korea", flag: "🇰🇷", code: "KOR" },
  { name: "India", flag: "🇮🇳", code: "IND" },
  { name: "Bahamas", flag: "🇧🇸", code: "BAH" },
  { name: "Jamaica", flag: "🇯🇲", code: "JAM" },
  { name: "Netherlands", flag: "🇳🇱", code: "NED" },
  { name: "Sweden", flag: "🇸🇪", code: "SWE" },
  { name: "Portugal", flag: "🇵🇹", code: "POR" },
  { name: "Switzerland", flag: "🇨🇭", code: "SUI" },

  // Every remaining sovereign state, alphabetical by region, so the search
  // bar covers the whole world — the basketball-relevant nations above stay
  // first since that's what most players will actually search for.
  // Africa
  { name: "Algeria", flag: "🇩🇿", code: "ALG" },
  { name: "Benin", flag: "🇧🇯", code: "BEN" },
  { name: "Botswana", flag: "🇧🇼", code: "BOT" },
  { name: "Burkina Faso", flag: "🇧🇫", code: "BUR" },
  { name: "Burundi", flag: "🇧🇮", code: "BDI" },
  { name: "Cape Verde", flag: "🇨🇻", code: "CPV" },
  { name: "Central African Republic", flag: "🇨🇫", code: "CAF" },
  { name: "Chad", flag: "🇹🇩", code: "CHA" },
  { name: "Comoros", flag: "🇰🇲", code: "COM" },
  { name: "Congo", flag: "🇨🇬", code: "CGO" },
  { name: "DR Congo", flag: "🇨🇩", code: "COD" },
  { name: "Djibouti", flag: "🇩🇯", code: "DJI" },
  { name: "Equatorial Guinea", flag: "🇬🇶", code: "GEQ" },
  { name: "Eritrea", flag: "🇪🇷", code: "ERI" },
  { name: "Eswatini", flag: "🇸🇿", code: "SWZ" },
  { name: "Ethiopia", flag: "🇪🇹", code: "ETH" },
  { name: "Gabon", flag: "🇬🇦", code: "GAB" },
  { name: "Gambia", flag: "🇬🇲", code: "GAM" },
  { name: "Ghana", flag: "🇬🇭", code: "GHA" },
  { name: "Guinea", flag: "🇬🇳", code: "GUI" },
  { name: "Guinea-Bissau", flag: "🇬🇼", code: "GBS" },
  { name: "Ivory Coast", flag: "🇨🇮", code: "CIV" },
  { name: "Kenya", flag: "🇰🇪", code: "KEN" },
  { name: "Lesotho", flag: "🇱🇸", code: "LES" },
  { name: "Liberia", flag: "🇱🇷", code: "LBR" },
  { name: "Libya", flag: "🇱🇾", code: "LBA" },
  { name: "Madagascar", flag: "🇲🇬", code: "MAD" },
  { name: "Malawi", flag: "🇲🇼", code: "MAW" },
  { name: "Mali", flag: "🇲🇱", code: "MLI" },
  { name: "Mauritania", flag: "🇲🇷", code: "MTN" },
  { name: "Mauritius", flag: "🇲🇺", code: "MRI" },
  { name: "Morocco", flag: "🇲🇦", code: "MAR" },
  { name: "Mozambique", flag: "🇲🇿", code: "MOZ" },
  { name: "Namibia", flag: "🇳🇦", code: "NAM" },
  { name: "Niger", flag: "🇳🇪", code: "NIG" },
  { name: "Rwanda", flag: "🇷🇼", code: "RWA" },
  { name: "Sao Tome and Principe", flag: "🇸🇹", code: "STP" },
  { name: "Sierra Leone", flag: "🇸🇱", code: "SLE" },
  { name: "Somalia", flag: "🇸🇴", code: "SOM" },
  { name: "South Africa", flag: "🇿🇦", code: "RSA" },
  { name: "Sudan", flag: "🇸🇩", code: "SUD" },
  { name: "Tanzania", flag: "🇹🇿", code: "TAN" },
  { name: "Togo", flag: "🇹🇬", code: "TOG" },
  { name: "Tunisia", flag: "🇹🇳", code: "TUN" },
  { name: "Uganda", flag: "🇺🇬", code: "UGA" },
  { name: "Zambia", flag: "🇿🇲", code: "ZAM" },
  { name: "Zimbabwe", flag: "🇿🇼", code: "ZIM" },
  // Americas
  { name: "Antigua and Barbuda", flag: "🇦🇬", code: "ANT" },
  { name: "Barbados", flag: "🇧🇧", code: "BAR" },
  { name: "Belize", flag: "🇧🇿", code: "BIZ" },
  { name: "Bolivia", flag: "🇧🇴", code: "BOL" },
  { name: "Costa Rica", flag: "🇨🇷", code: "CRC" },
  { name: "Cuba", flag: "🇨🇺", code: "CUB" },
  { name: "Dominica", flag: "🇩🇲", code: "DMA" },
  { name: "Ecuador", flag: "🇪🇨", code: "ECU" },
  { name: "El Salvador", flag: "🇸🇻", code: "ESA" },
  { name: "Grenada", flag: "🇬🇩", code: "GRN" },
  { name: "Guatemala", flag: "🇬🇹", code: "GUA" },
  { name: "Guyana", flag: "🇬🇾", code: "GUY" },
  { name: "Haiti", flag: "🇭🇹", code: "HAI" },
  { name: "Honduras", flag: "🇭🇳", code: "HON" },
  { name: "Nicaragua", flag: "🇳🇮", code: "NCA" },
  { name: "Paraguay", flag: "🇵🇾", code: "PAR" },
  { name: "Peru", flag: "🇵🇪", code: "PER" },
  { name: "Saint Kitts and Nevis", flag: "🇰🇳", code: "SKN" },
  { name: "Saint Lucia", flag: "🇱🇨", code: "LCA" },
  { name: "Saint Vincent and the Grenadines", flag: "🇻🇨", code: "VIN" },
  { name: "Suriname", flag: "🇸🇷", code: "SUR" },
  { name: "Trinidad and Tobago", flag: "🇹🇹", code: "TTO" },
  // Asia
  { name: "Afghanistan", flag: "🇦🇫", code: "AFG" },
  { name: "Armenia", flag: "🇦🇲", code: "ARM" },
  { name: "Azerbaijan", flag: "🇦🇿", code: "AZE" },
  { name: "Bahrain", flag: "🇧🇭", code: "BRN" },
  { name: "Bangladesh", flag: "🇧🇩", code: "BAN" },
  { name: "Bhutan", flag: "🇧🇹", code: "BHU" },
  { name: "Brunei", flag: "🇧🇳", code: "BRU" },
  { name: "Cambodia", flag: "🇰🇭", code: "CAM" },
  { name: "Cyprus", flag: "🇨🇾", code: "CYP" },
  { name: "East Timor", flag: "🇹🇱", code: "TLS" },
  { name: "Indonesia", flag: "🇮🇩", code: "INA" },
  { name: "Iraq", flag: "🇮🇶", code: "IRQ" },
  { name: "Jordan", flag: "🇯🇴", code: "JOR" },
  { name: "Kazakhstan", flag: "🇰🇿", code: "KAZ" },
  { name: "Kuwait", flag: "🇰🇼", code: "KUW" },
  { name: "Kyrgyzstan", flag: "🇰🇬", code: "KGZ" },
  { name: "Laos", flag: "🇱🇦", code: "LAO" },
  { name: "Lebanon", flag: "🇱🇧", code: "LBN" },
  { name: "Malaysia", flag: "🇲🇾", code: "MAS" },
  { name: "Maldives", flag: "🇲🇻", code: "MDV" },
  { name: "Mongolia", flag: "🇲🇳", code: "MGL" },
  { name: "Myanmar", flag: "🇲🇲", code: "MYA" },
  { name: "Nepal", flag: "🇳🇵", code: "NEP" },
  { name: "North Korea", flag: "🇰🇵", code: "PRK" },
  { name: "Oman", flag: "🇴🇲", code: "OMA" },
  { name: "Pakistan", flag: "🇵🇰", code: "PAK" },
  { name: "Qatar", flag: "🇶🇦", code: "QAT" },
  { name: "Saudi Arabia", flag: "🇸🇦", code: "KSA" },
  { name: "Singapore", flag: "🇸🇬", code: "SIN" },
  { name: "Sri Lanka", flag: "🇱🇰", code: "SRI" },
  { name: "Syria", flag: "🇸🇾", code: "SYR" },
  { name: "Taiwan", flag: "🇹🇼", code: "TPE" },
  { name: "Tajikistan", flag: "🇹🇯", code: "TJK" },
  { name: "Thailand", flag: "🇹🇭", code: "THA" },
  { name: "Turkmenistan", flag: "🇹🇲", code: "TKM" },
  { name: "United Arab Emirates", flag: "🇦🇪", code: "UAE" },
  { name: "Uzbekistan", flag: "🇺🇿", code: "UZB" },
  { name: "Vietnam", flag: "🇻🇳", code: "VIE" },
  { name: "Yemen", flag: "🇾🇪", code: "YEM" },
  // Europe
  { name: "Albania", flag: "🇦🇱", code: "ALB" },
  { name: "Andorra", flag: "🇦🇩", code: "AND" },
  { name: "Austria", flag: "🇦🇹", code: "AUT" },
  { name: "Belarus", flag: "🇧🇾", code: "BLR" },
  { name: "Belgium", flag: "🇧🇪", code: "BEL" },
  { name: "Bosnia and Herzegovina", flag: "🇧🇦", code: "BIH" },
  { name: "Bulgaria", flag: "🇧🇬", code: "BUL" },
  { name: "Czech Republic", flag: "🇨🇿", code: "CZE" },
  { name: "Denmark", flag: "🇩🇰", code: "DEN" },
  { name: "Estonia", flag: "🇪🇪", code: "EST" },
  { name: "Hungary", flag: "🇭🇺", code: "HUN" },
  { name: "Iceland", flag: "🇮🇸", code: "ISL" },
  { name: "Ireland", flag: "🇮🇪", code: "IRL" },
  { name: "Kosovo", flag: "🇽🇰", code: "KOS" },
  { name: "Liechtenstein", flag: "🇱🇮", code: "LIE" },
  { name: "Luxembourg", flag: "🇱🇺", code: "LUX" },
  { name: "Malta", flag: "🇲🇹", code: "MLT" },
  { name: "Moldova", flag: "🇲🇩", code: "MDA" },
  { name: "Monaco", flag: "🇲🇨", code: "MON" },
  { name: "North Macedonia", flag: "🇲🇰", code: "MKD" },
  { name: "Norway", flag: "🇳🇴", code: "NOR" },
  { name: "Romania", flag: "🇷🇴", code: "ROU" },
  { name: "Russia", flag: "🇷🇺", code: "RUS" },
  { name: "San Marino", flag: "🇸🇲", code: "SMR" },
  { name: "Slovakia", flag: "🇸🇰", code: "SVK" },
  { name: "Vatican City", flag: "🇻🇦", code: "VAT" },
  // Oceania
  { name: "Fiji", flag: "🇫🇯", code: "FIJ" },
  { name: "Kiribati", flag: "🇰🇮", code: "KIR" },
  { name: "Marshall Islands", flag: "🇲🇭", code: "MHL" },
  { name: "Micronesia", flag: "🇫🇲", code: "FSM" },
  { name: "Nauru", flag: "🇳🇷", code: "NRU" },
  { name: "Palau", flag: "🇵🇼", code: "PLW" },
  { name: "Papua New Guinea", flag: "🇵🇬", code: "PNG" },
  { name: "Samoa", flag: "🇼🇸", code: "SAM" },
  { name: "Solomon Islands", flag: "🇸🇧", code: "SOL" },
  { name: "Tonga", flag: "🇹🇴", code: "TGA" },
  { name: "Tuvalu", flag: "🇹🇻", code: "TUV" },
  { name: "Vanuatu", flag: "🇻🇺", code: "VAN" },
];

/** Forgiving search: partial name or code, case-insensitive. */
export function searchCountries(query: string): Country[] {
  const q = query.trim().toLowerCase();
  if (!q) return COUNTRIES;
  return COUNTRIES.filter(
    (c) => c.name.toLowerCase().includes(q) || c.code.toLowerCase().includes(q)
  );
}

export function findCountry(name: string): Country | undefined {
  const needle = name.trim().toLowerCase();
  return COUNTRIES.find((c) => c.name.toLowerCase() === needle || c.code.toLowerCase() === needle);
}

export function flagFor(name: string): string {
  return findCountry(name)?.flag ?? "🌍";
}
